### ISSUE TITLE
There is a problem with catkin_make

### ISSUE THREAD

**Issue by NanziZh** [nocholasrift/mpc_trajectory_tracking#1]
Hello, I installed ipopt and CppAD as required, but I encountered the following problems in the subsequent catkin_make. How should I solve them?
undefined reference to 'CppAD::local::temp_file[abi:cxx11]()'
![gnome-shell-screenshot-C8JSK2](https://github.com/nocholasrift/mpc_trajectory_tracking/assets/130638321/10fed894-c4b7-486b-b3f4-b376d14ce60b)
The above is translated using Google. Please forgive me if there are any problems.

**Comment by nocholasrift** [comment]
Hi there. One thing I can think of is perhaps there is an issue with the cppad version? When I run `dpkg -l cppad`, I get the following output:

![image](https://github.com/nocholasrift/mpc_trajectory_tracking/assets/31298312/fdd008a8-4e9d-4d7e-a24c-822309b43c7c)

If your version is different, maybe try installing the version I am using? If that ends up being the problem I can try to add a version requirement in the CMakefile or update the code-base to support newer versions of cppad. Please let me know if this helps!

**Comment by NanziZh** [comment]
The installation method I used was source code installation. I uninstalled the original one and found the 20190200 version on github. After installing it again, I used catkin_make and still encountered this problem.
![2](https://github.com/nocholasrift/mpc_trajectory_tracking/assets/130638321/7ba8a6bb-b2a8-4879-84c6-96a978c53037)

**Comment by nocholasrift** [comment]
If you provide additional details for how you installed both IPOPT and CppAD, I could try to recreate this issue. I've tested this code on several machines now in my lab and can't seem to recreate this specific error.

**Comment by NanziZh** [comment]
Since command line installation cannot be used, I installed both CppAD and Ipopt using source code. The specific installation steps are as follows.
The first one is Ipopt, first install the dependencies
`sudo apt-get install gcc g++ gfortran git patch wget pkg-config liblapack-dev libmetis-dev libblas-dev`
Then create the Ipopt folder and put all subsequent source codes in it for installation.

Install ASL
```
git clone https://github.com/coin-or-tools/ThirdParty-ASL.git
cd ThirdParty-ASL
sudo ./get.ASL
sudo ./configure
sudo make
sudo make install
cd..
```

Install HSL
```
git clone https://github.com/coin-or-tools/ThirdParty-HSL.git
cd ThirdParty-HSL
You need to download the installation package and extract it to the ThirdParty-HSL directory. The website is: https://github.com/CHH3213/testCPP/blob/master/coinhsl.zip
sudo ./configure
sudo make
sudo make install
cd..
```

Install MUMPS
```
git clone https://github.com/coin-or-tools/ThirdParty-Mumps.git
cd ThirdParty-Mumps
sudo ./get.Mumps
sudo ./configure
sudo make
sudo make install
cd..
```

Install Ipopt
```
git clone https://github.com/coin-or/Ipopt.git
cdIpopt
mkdir build
cd build
sudo ../configure
sudo make
sudo make test
sudo make install
```

Improve the environment
```
cd /usr/local/include
sudo cp coin-or coin -r
sudo ln -s /usr/local/lib/libcoinmumps.so.3 /usr/lib/libcoinmumps.so.3
sudo ln -s /usr/local/lib/libcoinhsl.so.2 /usr/lib/libcoinhsl.so.2
sudo ln -s /usr/local/lib/libipopt.so.3 /usr/lib/libipopt.so.3
```

The second is to install CppAD
```
git clone https://github.com/coin-or/CppAD.git
mkdir build
cd build
cmake..
make
sudo make install
```

**Comment by nocholasrift** [comment]
Hmmm, perhaps ASL and HSL are to blame here? When I built Ipopt, I only built and installed MUMPS and it worked fine. I would suggest trying without that and letting me know if that helps solve the issue.

**Comment by yifan96** [comment]
Same errors here.
Any updates?

**Comment by nocholasrift** [comment]
I'm attaching a bash script that I use to install ipopt on other systems, that can hopefully help. I would try installing everything in the way that is done in this script. Let me know if there are still issues. The only thing you need to install that isn't in this script is cppad, which can be installed from apt. 

```
# download ipopt
wget https://www.coin-or.org/download/source/Ipopt/Ipopt-3.14.4.tar.gz
tar -xf Ipopt-3.14.4.tar.gz

# build and install mumps
cd Ipopt-releases-3.14.4/
git clone https://github.com/coin-or-tools/ThirdParty-Mumps.git
cd ThirdParty-Mumps
./get.Mumps
mkdir build
cd build
../configure
make
make install

# build and install ipopt
cd ../..
mkdir build
cd build
../configure
make
make install

# fix naming issue from ipopt installation
cd /usr/local/include
cp -r coin-or coin
```

**Comment by yifan96** [comment]
Thanks for the quick response.
I do followed all the steps above, but the error is still there.
Not sure if it's the previous installation of ipopt having any conflict and it is not overwritten by the new installation. I followed [https://coin-or.github.io/Ipopt/INSTALL.html](https://coin-or.github.io/Ipopt/INSTALL.html) before, and i'm suspecting the author of this issue had this problem for the same reason.

**Comment by nocholasrift** [comment]
Let me try to follow the install steps that you both have been doing on a fresh machine. I'll see if I can recreate the issue and get back to you. Could be something with the cmake file. @yifan96 Could you also tell me what Ubuntu version you are using?

**Comment by nocholasrift** [comment]
@yifan96 @NanziZh I was able to reproduce the problem in Ubuntu 20.04. Seems both of you installed CppAD from source, and for some reason the libraries don't include some of methods used, even though they are present in the header files. 
**The fix:** Uninstall the CppAD that was installed from source, and instead get CppAD from `sudo apt install cppad`

This immediately fixed the issue on my end. Please let me know if that works for you as well.

**Comment by yifan96** [comment]
Working now!!
Thanks a lot :+1:

**Comment by nocholasrift** [comment]
Great, glad I could help :smile:, I'm going to close this issue but please feel free to reopen or make a new issue if anything arises.
